version: '3'

services:
  app:
    build: 
      context: ./app
      args:
        - WAZUH_MANAGER_IP=54.251.190.103
        - WAZUH_AGENT_NAME=sample-nodejs-app-agent-003
    networks:
      - sample-nodejs-network
    expose:
      - 3000

  app-wazuh-agent:
    build: 
      context: ../wazuh-agent-sidecar
      args:
        - WAZUH_MANAGER_IP=54.251.190.103
        - WAZUH_AGENT_NAME=sample-nodejs-agent-003
    networks:
      - sample-nodejs-network
    expose:
      - 1514

  envoy:
    build: 
      context: ../../envoy
      args:
        - WAZUH_MANAGER_IP=54.251.190.103
        - WAZUH_AGENT_NAME=sample-nodejs-envoy-agent-003
    networks:
      - sample-nodejs-network
    volumes:
      - ./logs/envoy:/var/log/envoy/tap
    ports:
      - "8080:8080"
      - "9901:9901"
    environment:
      ENVOY_UID: 0
      ENVOY_GID: 0
    privileged: true
    user: root

networks:
  sample-nodejs-network:
    driver: bridge